# @Time    : 2022-03-11 6:48 p.m.
# @Author  : Xiaoxia Li
# @FileName: lead.py
# @Software: PyCharm

from pacemaker.heart_object import Heart
from pacemaker.heart_controller import HearController

lead_A = "AtrialLead"
lead_V = "Ventricular"
A = "Atrial"
V = "Ventricular"
D = "Both"
O = "None"
I = "Inhibit"
T = "T"
pace_A = False
pace_V = False
sense_A = False
sense_V = False

class Lead:

    # define chamber
    @staticmethod
    def get_chamber(chamber):
        if chamber == A:
            return A
        if chamber == V:
            return V

    # define lead
    @staticmethod
    def add_lead(mode):
        if mode == "VAT" "DDD" "VDD":
            return lead_A, lead_V
        if mode == "AOO" "AAI":
            return lead_A
        if mode == "VOO" "VVI":
            return lead_V

    # 1. transit initial heart info from ECG to controller
    @staticmethod
    def transit_heart_info():
        initial_heart_info = Heart.heart_arr()
        return initial_heart_info
        # sensitivity, escape interval(after q, before p )

    # 2. Receive information from header
    # It can be expressed in terms of amplitude (volts, milliamps)
    # and pulse width (milliseconds), or energy (microjoules)
    # 起搏脉冲的波形是一个顶部略有下降的方波（如图2．11）。其幅度是指脉冲电压的最大值，一般取5V；其宽度是指脉冲的持续时间，多在0．5～1ms
    def stimulation(self):
        header_info = HearController.transit_pulse()
        return header_info

    # 3. Position 1 Chamber(s) Paced Standard Four-Letter Pacemaker Code\
    # pacing_therapy
    # cardiac depolarization
    def add_pace(self, chamber):
        if chamber == "A":
            return HearController.pace_atrium()
        elif chamber == "V":
            return HearController.pace_ventricle()
        elif chamber == "D":
            return HearController.pace_atrium(), HearController.pace_ventricle()

    # 4. Position 2 Chamber(s) Sensed
    # II chamber Sensed AVDO
    # input heart beat  output hear beat
    def add_sense(self, chamber):
        if chamber == "A":
            return HearController.sense_atrium()
        elif chamber == "V":
            return HearController.sense_ventricle()
        elif chamber == "D":
            return HearController.sense_atrium(), HearController.sense_ventricle()

    #5. Position 3 Response to Sensing
    # ITDO
    def add_response(self, mode):
        if mode == "I":
            return HearController.response_trigger()
        elif mode == "T":
            return HearController.response_inhibit()
        elif mode == "D":
            return HearController.response_trigger(), HearController.response_inhibit()
        else:
            return "None"

    # 6. stimulate
    # occurs T peak to before next q, stimulate V myocardial
    # stronger than normal stimulus can activate the V
    def stimulate(self, chamber):
        if chamber == "A":
            return HearController.a_stimulate()
        elif chamber == "V":
            return HearController.v_stimulate()
        else:
            return "None"

    #7.Modify information from heart/ECG
    def trainsit_output_heart(self):
        # initial_heart_info = Heart.heart_output()
        # return
         pass

    # 8. Is the absence of energy delivery to the heart.
    # Output:The electrical stimulus or energy generated by a pulse generator and
    # intended to trigger a depolarization in the chamber of the heart being paced.
    def atrial_output(self):

        pass

    # ventricular output pulse
    def ventricular_output(self):
        pass
